#!/usr/bin/env node
// Generate the tutor's theme CSS from Magnus's terminal themes, so the two apps
// share the same contrast-tuned colors (Heather, Lakeglow, Beacon, Hearth):
//   node scripts/build-themes.mjs [path/to/magnus]
// Reads magnus/terminal-theme/tools/colors.mjs at build time only; the output
// (web/src/styles/themes.css) is committed, so the tutor never depends on Magnus at runtime.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const magnus = path.resolve(process.argv[2] || path.join(here, '..', '..', 'magnus'));
const { FAMILIES, familyColors } = await import(pathToFileURL(path.join(magnus, 'terminal-theme', 'tools', 'colors.mjs')).href);

const blocks = [];
for (const fam of FAMILIES) {
  for (const mode of ['light', 'dark']) {
    const c = familyColors(fam, mode);
    const pal = c.g.pal;
    const vars = {
      '--bg': c.g.bg,
      '--surface': c.surface,
      '--surface-2': c.sidebar,
      '--hover': c.hover,
      '--subtle': c.subtleTo === '#ffffff' ? `rgba(255,255,255,${c.subtleAlpha})` : `rgba(0,0,0,${c.subtleAlpha})`,
      '--border': c.border,
      '--text': c.g.fg,
      '--muted': c.r.muted,
      '--accent': c.r.accent,
      '--accent-hover': c.accentHover,
      '--accent-tint': c.accentTint,
      '--on-accent': c.onAccent,
      '--danger': c.r.error,
      '--on-danger': c.onDanger,
      '--warning': c.r.warning,
      '--success': c.r.success,
      '--link': pal[4],
      '--violet': pal[5],
      '--teal': pal[6],
      '--shadow': c.dark ? '0 10px 30px rgba(0,0,0,0.35)' : '0 10px 30px rgba(40,30,20,0.10)',
      '--overlay': c.dark ? 'rgba(0,0,0,0.5)' : 'rgba(30,20,10,0.22)',
      'color-scheme': mode,
    };
    const sel = mode === 'dark' ? `[data-palette="${fam.key}"][data-mode="dark"]` : `[data-palette="${fam.key}"]`;
    blocks.push(`/* ${fam.label}, ${mode} */\n${sel} {\n${Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`).join('\n')}\n}`);
  }
}
const out = path.join(here, '..', 'web', 'src', 'styles', 'themes.css');
fs.writeFileSync(out, `/* Generated by scripts/build-themes.mjs from Magnus's terminal themes. Do not edit by hand. */\n\n${blocks.join('\n\n')}\n`);
fs.writeFileSync(path.join(here, '..', 'web', 'src', 'palettes.ts'),
  `// Generated by scripts/build-themes.mjs. Do not edit by hand.\nexport const PALETTES = ${JSON.stringify(FAMILIES.map(({ key, label }) => ({ key, label })))} as const;\n`);
console.log(`wrote ${out}`);
