// Generated by scripts/build-themes.mjs. Do not edit by hand.
export const PALETTES = [{"key":"hearth","label":"Hearth"},{"key":"heather","label":"Heather"},{"key":"lakeglow","label":"Lakeglow"},{"key":"beacon","label":"Beacon"}] as const;
